const legalTranslations = {
  fr: {
    pageTitle: "Mentions Légales - Rafael Antunes Oliveira",
    mainTitle: "Mentions Légales",
    theme: 'Thème',
    allRightsReserved: "Tous droits réservés",
    footerMentions: "Mentions Légales",
    navAccueil: "Accueil",
    navProjets: "Projets",
    navContact: "Contact",
    navAPropos: "À propos",
    navInfo: "Info",
    section1Title: "1. Identification de l'Éditeur",
    section1Name: "Nom : Rafael Antunes Oliveira",
    section1Age: "Âge : 19 ans",
    section1Status: "Statut : Étudiant en BUT MMI – Filière Développement",
    section1Email: "E-mail : rafael.atns.dev@gmail.com",
    section1Purpose: "Le présent site est un portfolio personnel présentant mes projets et compétences.",
    section2Title: "2. Hébergement",
    section2Host: "Hébergeur : Vercel Inc.",
    section2Address: "Adresse : 440 N Barranca Ave #4133, Covina, CA 91723, États-Unis",
    section2Web: "Site web : https://vercel.com",
    section3Title: "3. Propriété Intellectuelle",
    section3Content: "L’ensemble des contenus de ce site (textes, images, vidéos, projets, code, graphismes, logos…) est la propriété exclusive de Rafael Antunes Oliveira, sauf mention contraire.",
    section3Reproduction: "Toute reproduction, modification, redistribution ou exploitation sans autorisation est interdite.",
    section4Title: "4. Données personnelles – Formulaire de contact",
    section4DataUse: "Les informations collectées via le formulaire de contact (nom, e-mail, message) sont utilisées uniquement pour répondre aux demandes envoyées par l'utilisateur.",
    section4Processor: "Responsable du traitement : Rafael Antunes Oliveira",
    section4Purpose: "Finalité : Réponse aux demandes de contact",
    section4Retention: "Durée de conservation : 12 mois maximum",
    section4Recipient: "Destinataire : L’éditeur du site uniquement (aucun partage à des tiers)",
    section4RightsTitle: "Droits des utilisateurs",
    section4RightsIntro: "Conformément au RGPD, vous disposez des droits suivants :",
    rightAccess: "Droit d’accès",
    rightRectification: "Droit de rectification",
    rightErasure: "Droit à l’effacement",
    section4RightsContact: "Pour exercer vos droits : rafael.atns.dev@gmail.com",
    section5Title: "5. Cookies",
    section5None: "Ce site n’utilise aucun cookie de suivi ou de mesure d’audience.",
    section5Future: "Si un outil analytique est ajouté ultérieurement, cette section sera mise à jour.",
    section6Title: "6. Responsabilité",
    section6DisclaimerIntro: "L’éditeur du site ne peut être tenu responsable :",
    disclaimer1: "d’éventuelles erreurs ou omissions,",
    disclaimer2: "de problèmes d’accès au site,",
    disclaimer3: "de l’usage fait des contenus présents.",
  },
  en: {
    pageTitle: "Legal Notice - Rafael Antunes Oliveira",
    mainTitle: "Legal Notice",
    theme: 'Theme',
    allRightsReserved: "All rights reserved",
    footerMentions: "Legal Notice",
    navAccueil: "Home",
    navProjets: "Projects",
    navContact: "Contact",
    navAPropos: "About",
    navInfo: "Info",
    section1Title: "1. Editor Identification",
    section1Name: "Name: Rafael Antunes Oliveira",
    section1Age: "Age: 19 years old",
    section1Status: "Status: MMI BUT Student – Development Stream",
    section1Email: "Email: rafael.atns.dev@gmail.com",
    section1Purpose: "This website is a personal portfolio showcasing my projects and skills.",
    section2Title: "2. Hosting",
    section2Host: "Host: Vercel Inc.",
    section2Address: "Address: 440 N Barranca Ave #4133, Covina, CA 91723, United States",
    section2Web: "Website: https://vercel.com",
    section3Title: "3. Intellectual Property",
    section3Content: "All content on this site (texts, images, videos, projects, code, graphics, logos...) is the exclusive property of Rafael Antunes Oliveira, unless otherwise stated.",
    section3Reproduction: "Any reproduction, modification, redistribution, or exploitation without authorization is prohibited.",
    section4Title: "4. Personal Data – Contact Form",
    section4DataUse: "Information collected via the contact form (name, email, message) is used only to respond to user requests.",
    section4Processor: "Data Controller: Rafael Antunes Oliveira",
    section4Purpose: "Purpose: Response to contact requests",
    section4Retention: "Retention Period: 12 months maximum",
    section4Recipient: "Recipient: The site editor only (no sharing with third parties)",
    section4RightsTitle: "User Rights",
    section4RightsIntro: "In accordance with the GDPR, you have the following rights:",
    rightAccess: "Right of access",
    rightRectification: "Right of rectification",
    rightErasure: "Right to erasure",
    section4RightsContact: "To exercise your rights: rafael.atns.dev@gmail.com",
    section5Title: "5. Cookies",
    section5None: "This site does not use any tracking or audience measurement cookies.",
    section5Future: "If an analytical tool is added later, this section will be updated.",
    section6Title: "6. Liability",
    section6DisclaimerIntro: "The site editor cannot be held responsible for:",
    disclaimer1: "possible errors or omissions,",
    disclaimer2: "site access issues,",
    disclaimer3: "the use made of the content presented.",
  },
  pt: {
    pageTitle: "Aviso Legal - Rafael Antunes Oliveira",
    mainTitle: "Aviso Legal",
    theme: 'Tema',
    allRightsReserved: "Todos os direitos reservados",
    footerMentions: "Aviso Legal",
    navAccueil: "Início",
    navProjets: "Projetos",
    navContact: "Contato",
    navAPropos: "Sobre",
    navInfo: "Informações",
    section1Title: "1. Identificação do Editor",
    section1Name: "Nome: Rafael Antunes Oliveira",
    section1Age: "Idade: 19 anos",
    section1Status: "Status: Estudante BUT MMI – Ramo de Desenvolvimento",
    section1Email: "E-mail: rafael.atns.dev@gmail.com",
    section1Purpose: "Este site é um portfólio pessoal que apresenta meus projetos e competências.",
    section2Title: "2. Alojamento",
    section2Host: "Anfitrião: Vercel Inc.",
    section2Address: "Endereço: 440 N Barranca Ave #4133, Covina, CA 91723, Estados Unidos",
    section2Web: "Site: https://vercel.com",
    section3Title: "3. Propriedade Intelectual",
    section3Content: "Todo o conteúdo deste site (textos, imagens, vídeos, projetos, código, gráficos, logotipos...) é propriedade exclusiva de Rafael Antunes Oliveira, salvo indicação em contrário.",
    section3Reproduction: "Qualquer reprodução, modificação, redistribuição ou exploração sem autorização é proibida.",
    section4Title: "4. Dados Pessoais – Formulário de Contato",
    section4DataUse: "As informações coletadas através do formulário de contato (nome, e-mail, mensagem) são usadas apenas para responder às solicitações enviadas pelo utilizador.",
    section4Processor: "Responsável pelo tratamento: Rafael Antunes Oliveira",
    section4Purpose: "Finalidade: Resposta a pedidos de contacto",
    section4Retention: "Período de retenção: 12 meses no máximo",
    section4Recipient: "Destinatário: Apenas o editor do site (nenhuma partilha com terceiros)",
    section4RightsTitle: "Direitos do Utilizador",
    section4RightsIntro: "De acordo com o RGPD, você tem os seguintes direitos:",
    rightAccess: "Direito de acesso",
    rightRectification: "Direito de retificação",
    rightErasure: "Direito ao apagamento",
    section4RightsContact: "Para exercer seus direitos: rafael.atns.dev@gmail.com",
    section5Title: "5. Cookies",
    section5None: "Este site não usa cookies de rastreamento ou medição de audiência.",
    section5Future: "Se uma ferramenta analítica for adicionada posteriormente, esta seção será atualizada.",
    section6Title: "6. Responsabilidade",
    section6DisclaimerIntro: "O editor do site não pode ser responsabilizado por:",
    disclaimer1: "possíveis erros ou omissões,",
    disclaimer2: "problemas de acesso ao site,",
    disclaimer3: "o uso feito do conteúdo apresentado.",
  },
  es: {
    pageTitle: "Aviso Legal - Rafael Antunes Oliveira",
    mainTitle: "Aviso Legal",
    theme: 'Tema',
    allRightsReserved: "Todos los derechos reservados",
    footerMentions: "Aviso Legal",
    navAccueil: "Inicio",
    navProjets: "Proyectos",
    navContact: "Contacto",
    navAPropos: "Acerca de",
    navInfo: "Información",
    section1Title: "1. Identificación del Editor",
    section1Name: "Nombre: Rafael Antunes Oliveira",
    section1Age: "Edad: 19 años",
    section1Status: "Estado: Estudiante BUT MMI – Rama de Desarrollo",
    section1Email: "Correo electrónico: raf.atns1103@gmail.com",
    section1Purpose: "Este sitio es un portafolio personal que presenta mis proyectos y habilidades.",
    section2Title: "2. Alojamiento",
    section2Host: "Anfitrión: Vercel Inc.",
    section2Address: "Dirección: 440 N Barranca Ave #4133, Covina, CA 91723, Estados Unidos",
    section2Web: "Sitio web: https://vercel.com",
    section3Title: "3. Propiedad Intelectual",
    section3Content: "Todo el contenido de este sitio (textos, imágenes, videos, proyectos, código, gráficos, logotipos...) es propiedad exclusiva de Rafael Antunes Oliveira, salvo indicación contraria.",
    section3Reproduction: "Cualquier reproducción, modificación, redistribución o explotación sin autorización está prohibida.",
    section4Title: "4. Datos Personales – Formulario de Contacto",
    section4DataUse: "La información recopilada a través del formulario de contacto (nombre, correo electrónico, mensaje) se utiliza únicamente para responder a las solicitudes enviadas por el usuario.",
    section4Processor: "Responsable del tratamiento: Rafael Antunes Oliveira",
    section4Purpose: "Propósito: Respuesta a solicitudes de contacto",
    section4Retention: "Período de retención: 12 meses máximo",
    section4Recipient: "Destinatario: Solo el editor del sitio (sin compartir con terceros)",
    section4RightsTitle: "Derechos del Usuario",
    section4RightsIntro: "De conformidad con el RGPD, tiene los siguientes derechos:",
    rightAccess: "Derecho de acceso",
    rightRectification: "Derecho de rectificación",
    rightErasure: "Derecho al olvido",
    section4RightsContact: "Para ejercer sus derechos: raf.atns1103@gmail.com",
    section5Title: "5. Cookies",
    section5None: "Este sitio no utiliza cookies de seguimiento ni medición de audiencia.",
    section5Future: "Si se añade una herramienta analítica más adelante, esta sección se actualizará.",
    section6Title: "6. Responsabilidad",
    section6DisclaimerIntro: "El editor del sitio no puede ser responsable de:",
    disclaimer1: "posibles errores u omisiones,",
    disclaimer2: "problemas de acceso al sitio,",
    disclaimer3: "el uso que se haga del contenido presentado.",
  }
};

function applyLegalTranslations(lang) {
  const t = legalTranslations[lang] || legalTranslations.fr;
  
  document.title = t.pageTitle;
  
  document.getElementById('mainTitle').textContent = t.mainTitle;
  document.getElementById('themeBtn').textContent = t.theme;

  const elements = document.querySelectorAll('[data-translate]');
  elements.forEach(el => {
    const key = el.getAttribute('data-translate');
    if (t[key]) {
      el.innerHTML = t[key].replace('<strong>', '<strong>').replace('</strong>', '</strong>');
    }
  });
}

document.addEventListener('DOMContentLoaded', () => {
  const langSelect = document.getElementById('langSelect');
  let currentLang = localStorage.getItem('lang') || 'fr';
  
  applyLegalTranslations(currentLang);

  if (langSelect) {
    langSelect.addEventListener('change', (e) => {
      currentLang = e.target.value;
      localStorage.setItem('lang', currentLang);
      applyLegalTranslations(currentLang);
    });
  }
});